from aoc.input import InputParser
from aoc import log
from aoc.runner import Part

from year2025.day7.shared import TachyonMap


class Part2(Part):
    def run(self, parser: InputParser) -> int:
        input = parser.get_input()

        tachyon_map = TachyonMap(input)

        _, num_timelines = tachyon_map.shoot_beam()

        log.log(log.RESULT, f'The number of timelines a single tachyon ends up on: {num_timelines}')
        return num_timelines


part = Part2()

part.add_result(40, """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""")

part.add_result(15650261281478)
