from aoc.input import InputParser
from aoc import log
from aoc.runner import Part

from year2025.day7.shared import TachyonMap


class Part1(Part):
    def run(self, parser: InputParser) -> int:
        input = parser.get_input()

        tachyon_map = TachyonMap(input)

        num_splits, _ = tachyon_map.shoot_beam()

        log.log(log.RESULT, f'The number of splits of the tachyon beam: {num_splits}')
        return num_splits


part = Part1()

part.add_result(21, """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""")

part.add_result(1594)
